// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Fee struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	LevelID     int64     `json:"level_id"`
	PeriodStart time.Time `json:"period_start"`
	Amount      string    `json:"amount"`
	CreatedAt   time.Time `json:"created_at"`
}

type Level struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Amount    string    `json:"amount"`
	Active    bool      `json:"active"`
	CreatedAt time.Time `json:"created_at"`
}

type Payment struct {
	ID              int64          `json:"id"`
	UserID          sql.NullInt64  `json:"user_id"`
	Date            time.Time      `json:"date"`
	Amount          string         `json:"amount"`
	Kind            string         `json:"kind"`
	KindID          string         `json:"kind_id"`
	LocalAccount    string         `json:"local_account"`
	RemoteAccount   string         `json:"remote_account"`
	Identification  string         `json:"identification"`
	RawData         sql.NullString `json:"raw_data"`
	StaffComment    sql.NullString `json:"staff_comment"`
	CreatedAt       time.Time      `json:"created_at"`
	ProjectID       sql.NullInt64  `json:"project_id"`
	DismissedAt     interface{}    `json:"dismissed_at"`
	DismissedBy     interface{}    `json:"dismissed_by"`
	DismissedReason interface{}    `json:"dismissed_reason"`
}

type Project struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	PaymentsID  sql.NullString `json:"payments_id"`
	Description sql.NullString `json:"description"`
}

type ProjectV struct {
	ID        int64          `json:"id"`
	ProjectID int64          `json:"project_id"`
	Vs        string         `json:"vs"`
	Note      sql.NullString `json:"note"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type SystemLog struct {
	ID        int64          `json:"id"`
	Subsystem string         `json:"subsystem"`
	Level     string         `json:"level"`
	UserID    sql.NullInt64  `json:"user_id"`
	Message   string         `json:"message"`
	Metadata  sql.NullString `json:"metadata"`
	CreatedAt time.Time      `json:"created_at"`
}

type User struct {
	ID                int64          `json:"id"`
	KeycloakID        sql.NullString `json:"keycloak_id"`
	Email             string         `json:"email"`
	Username          sql.NullString `json:"username"`
	Realname          sql.NullString `json:"realname"`
	Phone             sql.NullString `json:"phone"`
	AltContact        sql.NullString `json:"alt_contact"`
	LevelID           int64          `json:"level_id"`
	LevelActualAmount string         `json:"level_actual_amount"`
	PaymentsID        sql.NullString `json:"payments_id"`
	DateJoined        time.Time      `json:"date_joined"`
	KeysGranted       sql.NullTime   `json:"keys_granted"`
	KeysReturned      sql.NullTime   `json:"keys_returned"`
	State             string         `json:"state"`
	IsCouncil         bool           `json:"is_council"`
	IsStaff           bool           `json:"is_staff"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}
